import turtle
nonte = turtle.Turtle()
fonte = turtle.Turtle()
tonte = turtle.Turtle()
nonte.shape("circle")
fonte.shape("square")
tonte.shape("triangle")
nonte.left(30)
fonte.forward(100)
tonte.forward(140)
monte = turtle.Turtle()
monte.setpos(-100, -100)
monte.forward(30)
monte.clear()
nonte.clear()
fonte.clear()
fonte.shape("triangle")
monte.shape("square")
